const departments = [
    "Accounting",
    "Adult Education",
    "Agricultural Engineering",
    "Agricultural Science and Education",
    "Agriculture",
    "Anatomy",
    "Arabic Studies",
    "Architecture",
    "Biochemistry",
    "Biological Sciences",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Computer Science",
    "Economics",
    "Education and Arabic",
    "Education and Biology",
    "Education and Chemistry",
    "Education and Computer Science",
    "Education and Economics",
    "Education and English Language",
    "Education and French",
    "Education and Geography",
    "Education and Hausa",
    "Education and History",
    "Education and Islamic Studies",
    "Education and Mathematics",
    "Education and Physics",
    "Education and Religious Studies",
    "Education and Social Studies",
    "Electrical Engineering",
    "English Language",
    "Estate Management",
    "Finance",
    "Fisheries and Aquaculture",
    "Forestry and Wildlife Management",
    "French",
    "Geography",
    "Geology",
    "Hausa",
    "History",
    "Industrial Chemistry",
    "Information Technology",
    "International Relations",
    "Islamic/Sharia Law",
    "Library and Information Science",
    "Linguistics",
    "Mass Communication",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Laboratory Science",
    "Medicine and Surgery",
    "Microbiology",
    "Nursing/Nursing Science",
    "Optometry",
    "Pharmacy",
    "Physical and Health Education",
    "Physics",
    "Physiology",
    "Political Science",
    "Public Administration",
    "Quantity Surveying",
    "Radiography",
    "Sociology",
    "Special Education",
    "Statistics",
    "Surveying and Geoinformatics",
    "Textile Science and Technology",
    "Theater Arts",
    "Urban and Regional Planning",
    "Zoology"
  ];
  
  export default departments;
  